services:
  postgres:
    image: postgres:16
    container_name: fuep_pg
    environment:
      POSTGRES_USER: fuep
      POSTGRES_PASSWORD: fuep
      POSTGRES_DB: fuep_portal
    ports:
      - '5432:5432'
    volumes:
      - ./infra/db:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U fuep -d fuep_portal']
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7
    container_name: fuep_redis
    ports:
      - '6379:6379'

  minio:
    image: minio/minio:latest
    container_name: fuep_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: fuep
      MINIO_ROOT_PASSWORD: fuepstrongpassword
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - miniodata:/data

  mailhog:
    image: mailhog/mailhog
    container_name: fuep_mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: runtime
    container_name: fuep_api
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=fuep
      - DB_PASSWORD=fuep
      - DB_NAME=fuep_portal
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=fuep
      - MINIO_SECRET_KEY=fuepstrongpassword
      - MINIO_USE_SSL=false
      - BRAND_PRIMARY_COLOR=FF134F47
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:4000/api/health || exit 1']
      interval: 10s
      timeout: 3s
      retries: 12

volumes:
  pgdata:
  miniodata:
